networks:
  app-net:
    driver: bridge

volumes:
  db-data:

services:
  frontend:
    image: acrmyappdevcentralindia001.azurecr.io/frontend:latest
    ports:
      - "8080:3000"
    restart: always

  backend:
   
    backend:
    image: acrmyappdevcentralindia001.azurecr.io/backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://dinijayo_db_user:dinijayo_db_user@cluster0.gkwvi5d.mongodb.net/todo_db?retryWrites=true&w=majority
    restart: always

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  volumes:
    mongo-data: