networks:
  app-net:
    driver: bridge

volumes:
  db-data:

services:
  frontend:
    # Pulling the pre-built image from ACR
    image: ${ACR_NAME}.azurecr.io/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-nets
    restart: unless-stopped

  backend:
   
    image: ${ACR_NAME}.azurecr.io/backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-net
    restart: unless-stopped
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  database:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}