networks:
  app-net:
    driver: bridge

volumes:
  db-data:

services:
  frontend:
    # Pulling the pre-built image from ACR
    image: ${ACR_NAME}.azurecr.io/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-nets
    restart: unless-stopped

  backend:
   
    image: ${ACR_NAME}.azurecr.io/backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-net
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}

  database:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}

  volumes:
    mongo-data: