name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    # This addresses the Node 20 warning
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t my-backend:latest ./backend

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-backend:latest'
          format: 'table'
          # We'll keep exit-code 1 to stay secure!
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'