name: CD - Deploy to Azure

on:
  workflow_run:
    workflows: ["CI Pipeline"] # Ensures CD only triggers after CI Success
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run this job if the CI Pipeline actually passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Deploying to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # 1. Create and Enter the application directory
            mkdir -p ~/my-3tier-app
            cd ~/my-3tier-app

            # 2. Clone the repo if missing, otherwise pull the latest changes
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git pull origin main
            fi

            # 3. Create .env file dynamically (Step 5: Secrets Management)
            # This pulls from your GitHub Secrets and creates the file on the VM
            echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_PORT=5432" >> .env

            # 4. Deploy/Restart the containers (Step 7 & 11)
            # --build ensures fresh images are created if the code changed
            docker compose up -d --build

            # 5. Clean up old, unused images to save VM storage (Step 3)
            docker image prune -f
      - name: Notify Discord on Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "🚀 **Deployment Successful!** App is live at http://40.81.30.7:8080"
          title: "CD Pipeline Result"
          color: 0x00ff00

      - name: Notify Discord on Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "⚠️ **Deployment Failed!** Check GitHub Actions logs for details."
          title: "CD Pipeline Result"
          color: 0xff0000
  