name: CD - Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    
    steps:
      - name: Deploying to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            # 1. Enter the Deployment Directory
            cd ~/my-3tier-app
            
            # 2. Sync with the latest code from GitHub
            git pull origin main 

            # 3. THE ASSEMBLER: Delete old local folders and clone fresh 
          
            rm -rf frontend backend
            git clone https://github.com/2003dinijay/my-app-frontend.git frontend
            git clone https://github.com/2003dinijay/my-app-backend.git backend

            # 4. Deploy the 3-Tier System
            docker compose up -d --build
            
            # 5. Cleanup old images to save Azure disk space
            docker image prune -f
      - name: Notify Discord on Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "🚀 **Deployment Successful!** App is live at http://40.81.30.7:8080"
          title: "CD Pipeline Result"
          color: 0x00ff00

      - name: Notify Discord on Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "⚠️ **Deployment Failed!** Check GitHub Actions logs for details."
          title: "CD Pipeline Result"
          color: 0xff0000
  